project_root: /home/minh/PycharmProjects/prostate_cancer_classification_v1
tasks: [ 'cls', ]
tasks_num_class: [ 2, ]
input_channels: [ 1, ]
num_workers: 15
model_name: coteaching
self_train: False
variational: False
multitask: False
is_eval: True

paths: # 'exp_name' will be replaced by actual experiment name
  log_dir: experiments/exp_name/logs
  result_dir: experiments/exp_name/results
  checkpoint_dir: experiments/exp_name/checkpoints
  self_train_checkpoint: 'ckpt2/inception/SelfTime/ProstateTeUS/magnitude_warp_time_warp/0.2_3C/0/backbone_best.tar'

data_source:
  dataset: ProstateTeUS
  data_root: datasets
  train_set: BK_RF_P1_140_balance__20210203-175808_mimic.pkl  # BK_RF_P1_140_balance__20201127-104536.mat
  test_set: BK_RF_P1_140_balance__20210203-175808_mimic.pkl

# Tunable (iteratively) hyper-parameters
seed: 0
n_epochs: 100
backbone: [ inception, inception ]
exp_name: coteaching
exp_suffix: ''
normalize_input: none
min_inv: .4

arch:
  # inception
  num_blocks: 3
  out_channels: 64
  # resnet
  mid_channels: 32
  num_positions: 0

test:
  test_interval: 1
  which_iter: best
  batch_size: 4096
